# Site settings
title: Keegan Berry - Web Developer in Orlando Florida
email: me@keeganberry.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site

twitter_username: keegan
instagram_username: keeganberry
flickr_urlname: superdeathsquid
linkedin_profile_url: https://www.linkedin.com/in/keegan-berry-5528a713
github_username:  keeeeeegan
github_url: https://github.com/keeeeeegan/new-site

contact_form_action: http://formspree.io/keeganberry@gmail.com

ga_property: "UA-26787049-1"

# Build settings
markdown: kramdown

# Collections (work)
collections:
  work:
    output: true
    permalink: /work/:path/
