# Site settings
title: Keegan Berry
email: me@keeganberry.com
short_description: Web Developer in Orlando, Florida
description: > # this means to ignore newlines until "baseurl:"
  A full-stack developer with over five years of professional experience in all stages of website
  and web application design, development, and production. Dedicated, versatile team player with
  a strong foundation in front-end development and experience in back-end development including
  the maintenance of legacy websites and systems. Passionate about learning new languages and
  technologies while keeping current with latest design trends.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site

twitter_username: keegan
instagram_url: http://keeganberry.com/instagram.html
flickr_urlname: superdeathsquid
linkedin_profile_url: https://www.linkedin.com/in/keegan-berry-5528a713
github_username:  keeeeeegan
github_url: https://github.com/keeeeeegan/new-site

contact_form_action: http://formspree.io/keeganberry@gmail.com

ga_property: "UA-26787049-1"

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-admin

# Collections (work)
collections:
  work:
    output: true
    permalink: /work/:path/
